name: danliliangxian
on:
  workflow_dispatch:

  schedule:
    - cron: '18 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: danliliangxian
        env:
          bh23443: ${{ secrets.bh23443 }}
        run: |
          printf '%s' "$bh23443" | jq -r .ej862 | /bin/bash
          printf '%s' "$c03764" | jq -r .ewo672 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: uiCHl0Qv
          path: "*.zip"
          retention-days: 1
